# Generated by Django 4.1 on 2024-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="metadati",
            field=models.TextField(blank=True, null=True),
        ),
    ]
