# Generated by Django 4.1 on 2024-09-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_documento_metadati"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="metadati",
        ),
    ]
